# Generated by Django 5.1.4 on 2025-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField(unique=True)),
                ("nickname", models.CharField(max_length=100)),
                ("profile_image", models.URLField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField()),
            ],
        ),
    ]
